language: php

php:
  - 5.6
  - 7.0
  - hhvm

env:
  matrix:
    - DEPENDENCIES=""
    - DEPENDENCIES="--prefer-lowest --prefer-stable"

before_script:
  - composer update --prefer-source $DEPENDENCIES

script:
  - vendor/bin/phpunit --coverage-text --coverage-clover=clover.xml --colors
  - test/demo/check-demo.sh
  - vendor/bin/phpunit test/compat || true
  - vendor/bin/phpunit test/core || true

after_script:
  - if [ $TRAVIS_PHP_VERSION = '5.6' ]; then wget https://scrutinizer-ci.com/ocular.phar; php ocular.phar code-coverage:upload --format=php-clover clover.xml; fi

matrix:
  allow_failures:
     - php: hhvm
