language: php

php:
  - 7.1

env:
  matrix:
    - DEPENDENCIES=""
    - DEPENDENCIES="--prefer-lowest --prefer-stable"

before_script:
  - composer update --prefer-dist $DEPENDENCIES

script:
  - vendor/bin/phpunit --coverage-text --coverage-clover=clover.xml --colors
  - test/demo/check-demo.sh
  - vendor/bin/phpunit test/compat

after_script:
  - if [ $TRAVIS_PHP_VERSION = '7.0' ]; then wget https://scrutinizer-ci.com/ocular.phar; php ocular.phar code-coverage:upload --format=php-clover clover.xml; fi
