os: linux
dist: xenial
language: php

if: type != push OR branch = master OR branch =~ /^v?\d+\.\d+(\.\d+)?(-\S*)?$/

before_script:
  - rm composer.lock
  - travis_retry composer update --prefer-dist $DEPENDENCIES

jobs:
  include:
    - stage: Test
      php: 7.2
      env: DEPENDENCIES=""
      script: vendor/bin/phpunit

    - stage: Test
      php: 7.2
      env: DEPENDENCIES="--prefer-lowest --prefer-stable"
      script: vendor/bin/phpunit

    - stage: Test
      os: windows
      language: shell # No PHP currently
      env: PHP_VERSION=7.2.26 DEPENDENCIES=""
      install:
        - choco install php --version=${PHP_VERSION} --package-parameters="/InstallDir:c:\tools\php"
        - choco install composer --ia "/DEV=C:\tools\php"
        - export PATH=/c/tools/php:$PATH
        - echo "memory_limit=1G" >> /c/tools/php/php.ini
      script: vendor/bin/phpunit

    - stage: Test
      os: windows
      language: shell # No PHP currently
      env: PHP_VERSION=7.2.26 DEPENDENCIES="--prefer-lowest --prefer-stable"
      install:
        - choco install php --version=${PHP_VERSION} --package-parameters="/InstallDir:c:\tools\php"
        - choco install composer --ia "/DEV=C:\tools\php"
        - export PATH=/c/tools/php:$PATH
        - echo "memory_limit=1G" >> /c/tools/php/php.ini
      script: vendor/bin/phpunit

    - stage: Test
      php: 7.3
      env: DEPENDENCIES=""
      script: vendor/bin/phpunit

    - stage: Test
      php: 7.3
      env: DEPENDENCIES="--prefer-lowest --prefer-stable"
      script: vendor/bin/phpunit

    - stage: Test
      os: windows
      language: shell # No PHP currently
      env: PHP_VERSION=7.3.13 DEPENDENCIES=""
      install:
        - choco install php --version=${PHP_VERSION} --package-parameters="/InstallDir:c:\tools\php"
        - choco install composer --ia "/DEV=C:\tools\php"
        - export PATH=/c/tools/php:$PATH
        - echo "memory_limit=1G" >> /c/tools/php/php.ini
      script: vendor/bin/phpunit

    - stage: Test
      os: windows
      language: shell # No PHP currently
      env: PHP_VERSION=7.3.13 DEPENDENCIES="--prefer-lowest --prefer-stable"
      install:
        - choco install php --version=${PHP_VERSION} --package-parameters="/InstallDir:c:\tools\php"
        - choco install composer --ia "/DEV=C:\tools\php"
        - export PATH=/c/tools/php:$PATH
        - echo "memory_limit=1G" >> /c/tools/php/php.ini
      script: vendor/bin/phpunit

    - stage: Test
      php: 7.4
      env: DEPENDENCIES=""
      script: vendor/bin/phpunit

    - stage: Test
      php: 7.4
      env: DEPENDENCIES="--prefer-lowest --prefer-stable"
      script: vendor/bin/phpunit

    - stage: Test
      os: windows
      language: shell # No PHP currently
      env: PHP_VERSION=7.4.1 DEPENDENCIES=""
      install:
        - choco install php --version=${PHP_VERSION} --package-parameters="/InstallDir:c:\tools\php"
        - choco install composer --ia "/DEV=C:\tools\php"
        - export PATH=/c/tools/php:$PATH
        - echo "memory_limit=1G" >> /c/tools/php/php.ini
      script: vendor/bin/phpunit

    - stage: Test
      os: windows
      language: shell # No PHP currently
      env: PHP_VERSION=7.4.1 DEPENDENCIES="--prefer-lowest --prefer-stable"
      install:
        - choco install php --version=${PHP_VERSION} --package-parameters="/InstallDir:c:\tools\php"
        - choco install composer --ia "/DEV=C:\tools\php"
        - export PATH=/c/tools/php:$PATH
        - echo "memory_limit=1G" >> /c/tools/php/php.ini
      script: vendor/bin/phpunit

    - stage: Test Compatibility
      php: 7.2
      env: DEPENDENCIES=""
      script: vendor/bin/phpunit test/compat

    - stage: Test Compatibility
      php: 7.2
      env: DEPENDENCIES="--prefer-lowest --prefer-stable"
      script: vendor/bin/phpunit test/compat

    - stage: Test Compatibility
      os: windows
      language: shell # No PHP currently
      env: PHP_VERSION=7.2.26 DEPENDENCIES=""
      install:
        - choco install php --version=${PHP_VERSION} --package-parameters="/InstallDir:c:\tools\php"
        - choco install composer --ia "/DEV=C:\tools\php"
        - export PATH=/c/tools/php:$PATH
        - echo "memory_limit=1G" >> /c/tools/php/php.ini
      script: vendor/bin/phpunit test/compat

    - stage: Test Compatibility
      os: windows
      language: shell # No PHP currently
      env: PHP_VERSION=7.2.26 DEPENDENCIES="--prefer-lowest --prefer-stable"
      install:
        - choco install php --version=${PHP_VERSION} --package-parameters="/InstallDir:c:\tools\php"
        - choco install composer --ia "/DEV=C:\tools\php"
        - export PATH=/c/tools/php:$PATH
        - echo "memory_limit=1G" >> /c/tools/php/php.ini
      script: vendor/bin/phpunit test/compat

    - stage: Test Compatibility
      php: 7.3
      env: DEPENDENCIES=""
      script: vendor/bin/phpunit test/compat

    - stage: Test Compatibility
      php: 7.3
      env: DEPENDENCIES="--prefer-lowest --prefer-stable"
      script: vendor/bin/phpunit test/compat

    - stage: Test Compatibility
      os: windows
      language: shell # No PHP currently
      env: PHP_VERSION=7.3.13 DEPENDENCIES=""
      install:
        - choco install php --version=${PHP_VERSION} --package-parameters="/InstallDir:c:\tools\php"
        - choco install composer --ia "/DEV=C:\tools\php"
        - export PATH=/c/tools/php:$PATH
        - echo "memory_limit=1G" >> /c/tools/php/php.ini
      script: vendor/bin/phpunit test/compat

    - stage: Test Compatibility
      os: windows
      language: shell # No PHP currently
      env: PHP_VERSION=7.3.13 DEPENDENCIES="--prefer-lowest --prefer-stable"
      install:
        - choco install php --version=${PHP_VERSION} --package-parameters="/InstallDir:c:\tools\php"
        - choco install composer --ia "/DEV=C:\tools\php"
        - export PATH=/c/tools/php:$PATH
        - echo "memory_limit=1G" >> /c/tools/php/php.ini
      script: vendor/bin/phpunit test/compat

    - stage: Test Compatibility
      php: 7.4
      env: DEPENDENCIES=""
      script: vendor/bin/phpunit test/compat

    - stage: Test Compatibility
      php: 7.4
      env: DEPENDENCIES="--prefer-lowest --prefer-stable"
      script: vendor/bin/phpunit test/compat

    - stage: Test Compatibility
      os: windows
      language: shell # No PHP currently
      env: PHP_VERSION=7.4.1 DEPENDENCIES=""
      install:
        - choco install php --version=${PHP_VERSION} --package-parameters="/InstallDir:c:\tools\php"
        - choco install composer --ia "/DEV=C:\tools\php"
        - export PATH=/c/tools/php:$PATH
        - echo "memory_limit=1G" >> /c/tools/php/php.ini
      script: vendor/bin/phpunit test/compat

    - stage: Test Compatibility
      os: windows
      language: shell # No PHP currently
      env: PHP_VERSION=7.4.1 DEPENDENCIES="--prefer-lowest --prefer-stable"
      install:
        - choco install php --version=${PHP_VERSION} --package-parameters="/InstallDir:c:\tools\php"
        - choco install composer --ia "/DEV=C:\tools\php"
        - export PATH=/c/tools/php:$PATH
        - echo "memory_limit=1G" >> /c/tools/php/php.ini
      script: vendor/bin/phpunit test/compat

    - stage: Check Demo Scripts
      php: 7.2
      env: DEPENDENCIES=""
      script: test/demo/check-demo.sh

    - stage: Check Demo Scripts
      php: 7.2
      env: DEPENDENCIES="--prefer-lowest --prefer-stable"
      script: test/demo/check-demo.sh

    - stage: Check Demo Scripts
      php: 7.3
      env: DEPENDENCIES=""
      script: test/demo/check-demo.sh

    - stage: Check Demo Scripts
      php: 7.3
      env: DEPENDENCIES="--prefer-lowest --prefer-stable"
      script: test/demo/check-demo.sh

    - stage: Check Demo Scripts
      php: 7.4
      env: DEPENDENCIES=""
      script: test/demo/check-demo.sh

    - stage: Check Demo Scripts
      php: 7.4
      env: DEPENDENCIES="--prefer-lowest --prefer-stable"
      script: test/demo/check-demo.sh

    - stage: Check Coding Standard
      php: 7.4
      env: DEPENDENCIES=""
      before_script:
        - travis_retry composer install
      script: vendor/bin/phpcs

    - stage: Static Analysis
      php: 7.4
      env: DEPENDENCIES=""
      script: vendor/bin/phpstan analyse --memory-limit=-1

    - stage: Static Analysis
      php: 7.4
      env: DEPENDENCIES=""
      script: vendor/bin/psalm --shepherd --stats

    - stage: Run benchmarks
      php: 7.4
      env: DEPENDENCIES=""
      before_script:
        - travis_retry composer require --dev --prefer-dist --prefer-stable phpbench/phpbench:^0.16.9
      script: ./vendor/bin/phpbench run --progress=dots --iterations=1

    - stage: Upload Coverage
      php: 7.4
      env: DEPENDENCIES=""
      before_script:
        - travis_retry composer update --prefer-dist $DEPENDENCIES
        - wget https://scrutinizer-ci.com/ocular.phar
      script:
        - vendor/bin/phpunit --dump-xdebug-filter=xdebug-filter.php
        - vendor/bin/phpunit --coverage-text --coverage-clover=clover.xml --prepend=xdebug-filter.php
        - php ocular.phar code-coverage:upload --format=php-clover clover.xml

cache:
  directories:
    - $HOME/.composer/cache
